// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/include/flutter_ffi_uvc.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterFfiUvcBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterFfiUvcBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterFfiUvcBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Allocates an idle session. Returns NULL on allocation failure.
  ffi.Pointer<uvc_session_t> uvc_session_create() {
    return _uvc_session_create();
  }

  late final _uvc_session_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<uvc_session_t> Function()>>(
        'uvc_session_create',
      );
  late final _uvc_session_create = _uvc_session_createPtr
      .asFunction<ffi.Pointer<uvc_session_t> Function()>();

  /// uvc_request_destroy without a report. Queues the teardown and returns at
  /// once, so it is safe to call from a garbage collector or any thread that
  /// must not block. No listener fires afterwards.
  void uvc_session_destroy(ffi.Pointer<uvc_session_t> session) {
    return _uvc_session_destroy(session);
  }

  late final _uvc_session_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_session_destroy');
  late final _uvc_session_destroy = _uvc_session_destroyPtr
      .asFunction<void Function(ffi.Pointer<uvc_session_t>)>();

  /// For callers that hold a session pointer they do not own. uvc_session_acquire
  /// returns 1 and pins the session when the pointer is a live session, and 0
  /// for any other pointer. Pair every successful acquire with a release.
  int uvc_session_acquire(ffi.Pointer<uvc_session_t> session) {
    return _uvc_session_acquire(session);
  }

  late final _uvc_session_acquirePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<uvc_session_t>)>>(
        'uvc_session_acquire',
      );
  late final _uvc_session_acquire = _uvc_session_acquirePtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  void uvc_session_release(ffi.Pointer<uvc_session_t> session) {
    return _uvc_session_release(session);
  }

  late final _uvc_session_releasePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_session_release');
  late final _uvc_session_release = _uvc_session_releasePtr
      .asFunction<void Function(ffi.Pointer<uvc_session_t>)>();

  /// Registry id of a session. Unique for the life of the process and never
  /// reused, so a holder can name a session that may have been destroyed since.
  /// Platform plugin layers key their state by this id, not by the pointer.
  int uvc_session_id(ffi.Pointer<uvc_session_t> session) {
    return _uvc_session_id(session);
  }

  late final _uvc_session_idPtr =
      _lookup<
        ffi.NativeFunction<ffi.Uint64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_session_id');
  late final _uvc_session_id = _uvc_session_idPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// Pins the session with that id, as uvc_session_acquire does. Returns NULL
  /// when no live session has it. Release with uvc_session_release.
  ffi.Pointer<uvc_session_t> uvc_session_acquire_id(int id) {
    return _uvc_session_acquire_id(id);
  }

  late final _uvc_session_acquire_idPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<uvc_session_t> Function(ffi.Uint64)>
      >('uvc_session_acquire_id');
  late final _uvc_session_acquire_id = _uvc_session_acquire_idPtr
      .asFunction<ffi.Pointer<uvc_session_t> Function(int)>();

  /// Synchronous lifecycle. These block the calling thread and bypass the
  /// request queue below, which is built on them. The Dart layer uses the
  /// queue. Opens a device on the session. fd is a USB device node descriptor
  /// on Android and Linux and the enumeration device id on Windows. A device
  /// already open on this session is closed first.
  int uvc_open_fd(ffi.Pointer<uvc_session_t> session, int fd) {
    return _uvc_open_fd(session, fd);
  }

  late final _uvc_open_fdPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Int)
        >
      >('uvc_open_fd');
  late final _uvc_open_fd = _uvc_open_fdPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int)>();

  int uvc_start_preview(
    ffi.Pointer<uvc_session_t> session,
    int frame_format,
    int width,
    int height,
    int fps,
  ) {
    return _uvc_start_preview(session, frame_format, width, height, fps);
  }

  late final _uvc_start_previewPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('uvc_start_preview');
  late final _uvc_start_preview = _uvc_start_previewPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, int, int, int, int)
      >();

  void uvc_stop_preview(ffi.Pointer<uvc_session_t> session) {
    return _uvc_stop_preview(session);
  }

  late final _uvc_stop_previewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_stop_preview');
  late final _uvc_stop_preview = _uvc_stop_previewPtr
      .asFunction<void Function(ffi.Pointer<uvc_session_t>)>();

  void uvc_close_device(ffi.Pointer<uvc_session_t> session) {
    return _uvc_close_device(session);
  }

  late final _uvc_close_devicePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_close_device');
  late final _uvc_close_device = _uvc_close_devicePtr
      .asFunction<void Function(ffi.Pointer<uvc_session_t>)>();

  int uvc_is_previewing(ffi.Pointer<uvc_session_t> session) {
    return _uvc_is_previewing(session);
  }

  late final _uvc_is_previewingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<uvc_session_t>)>>(
        'uvc_is_previewing',
      );
  late final _uvc_is_previewing = _uvc_is_previewingPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  int uvc_frame_width(ffi.Pointer<uvc_session_t> session) {
    return _uvc_frame_width(session);
  }

  late final _uvc_frame_widthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<uvc_session_t>)>>(
        'uvc_frame_width',
      );
  late final _uvc_frame_width = _uvc_frame_widthPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  int uvc_frame_height(ffi.Pointer<uvc_session_t> session) {
    return _uvc_frame_height(session);
  }

  late final _uvc_frame_heightPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<uvc_session_t>)>>(
        'uvc_frame_height',
      );
  late final _uvc_frame_height = _uvc_frame_heightPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  int uvc_copy_latest_frame_rgba(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_copy_latest_frame_rgba(session, buffer, buffer_length);
  }

  late final _uvc_copy_latest_frame_rgbaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_copy_latest_frame_rgba');
  late final _uvc_copy_latest_frame_rgba = _uvc_copy_latest_frame_rgbaPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_copy_latest_frame_rgba_with_metadata(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
    ffi.Pointer<ffi.Int64> out_sequence,
  ) {
    return _uvc_copy_latest_frame_rgba_with_metadata(
      session,
      buffer,
      buffer_length,
      out_width,
      out_height,
      out_sequence,
    );
  }

  late final _uvc_copy_latest_frame_rgba_with_metadataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('uvc_copy_latest_frame_rgba_with_metadata');
  late final _uvc_copy_latest_frame_rgba_with_metadata =
      _uvc_copy_latest_frame_rgba_with_metadataPtr
          .asFunction<
            int Function(
              ffi.Pointer<uvc_session_t>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int64>,
            )
          >();

  int uvc_copy_latest_frame_rgba_transformed(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
    int rotation,
    int flip_h,
    int flip_v,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
    ffi.Pointer<ffi.Int64> out_sequence,
  ) {
    return _uvc_copy_latest_frame_rgba_transformed(
      session,
      buffer,
      buffer_length,
      rotation,
      flip_h,
      flip_v,
      out_width,
      out_height,
      out_sequence,
    );
  }

  late final _uvc_copy_latest_frame_rgba_transformedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('uvc_copy_latest_frame_rgba_transformed');
  late final _uvc_copy_latest_frame_rgba_transformed =
      _uvc_copy_latest_frame_rgba_transformedPtr
          .asFunction<
            int Function(
              ffi.Pointer<uvc_session_t>,
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              int,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int64>,
            )
          >();

  int uvc_latest_frame_sequence(ffi.Pointer<uvc_session_t> session) {
    return _uvc_latest_frame_sequence(session);
  }

  late final _uvc_latest_frame_sequencePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_latest_frame_sequence');
  late final _uvc_latest_frame_sequence = _uvc_latest_frame_sequencePtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  void uvc_set_frame_listener(
    ffi.Pointer<uvc_session_t> session,
    uvc_frame_listener_t listener,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _uvc_set_frame_listener(session, listener, user_data);
  }

  late final _uvc_set_frame_listenerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<uvc_session_t>,
            uvc_frame_listener_t,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('uvc_set_frame_listener');
  late final _uvc_set_frame_listener = _uvc_set_frame_listenerPtr
      .asFunction<
        void Function(
          ffi.Pointer<uvc_session_t>,
          uvc_frame_listener_t,
          ffi.Pointer<ffi.Void>,
        )
      >();

  void uvc_set_error_listener(
    ffi.Pointer<uvc_session_t> session,
    uvc_error_listener_t listener,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _uvc_set_error_listener(session, listener, user_data);
  }

  late final _uvc_set_error_listenerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<uvc_session_t>,
            uvc_error_listener_t,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('uvc_set_error_listener');
  late final _uvc_set_error_listener = _uvc_set_error_listenerPtr
      .asFunction<
        void Function(
          ffi.Pointer<uvc_session_t>,
          uvc_error_listener_t,
          ffi.Pointer<ffi.Void>,
        )
      >();

  void uvc_set_request_listener(
    ffi.Pointer<uvc_session_t> session,
    uvc_request_listener_t listener,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _uvc_set_request_listener(session, listener, user_data);
  }

  late final _uvc_set_request_listenerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<uvc_session_t>,
            uvc_request_listener_t,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('uvc_set_request_listener');
  late final _uvc_set_request_listener = _uvc_set_request_listenerPtr
      .asFunction<
        void Function(
          ffi.Pointer<uvc_session_t>,
          uvc_request_listener_t,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// Every request function returns an id unique for the life of the process
  /// and never reused, so a platform plugin may key its own state by it.
  ///
  /// Queues an open. The worker closes the device the session holds, then
  /// waits for uvc_supply_fd with this request id. A close queued meanwhile
  /// ends the wait with UVC_ERROR_INTERRUPTED. An fd already supplied is
  /// opened, and the close then takes it back. A stop leaves opens alone.
  int uvc_request_open(ffi.Pointer<uvc_session_t> session) {
    return _uvc_request_open(session);
  }

  late final _uvc_request_openPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_request_open');
  late final _uvc_request_open = _uvc_request_openPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// Hands the fd (or Windows device id) to a queued open. fd < 0 fails the
  /// open with UVC_ERROR_NO_DEVICE. Returns 0 when the request took the fd,
  /// which the session then owns until it reports device_released, and
  /// UVC_ERROR_INVALID_PARAM when no such open is waiting, in which case the
  /// caller still owns the fd.
  int uvc_supply_fd(
    ffi.Pointer<uvc_session_t> session,
    int request_id,
    int fd,
  ) {
    return _uvc_supply_fd(session, request_id, fd);
  }

  late final _uvc_supply_fdPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Int64, ffi.Int)
        >
      >('uvc_supply_fd');
  late final _uvc_supply_fd = _uvc_supply_fdPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int)>();

  /// Queues a stream start with verification. timeout_ms bounds the
  /// verification. The result JSON is readable with
  /// uvc_take_request_result_json until the next start or auto completes:
  /// {"success":bool,"validFrameCount":n,"consecutiveValidFrames":n,
  /// "errorCount":n,"elapsedMs":n,"lastError":"..","nativeErrorCode":n,
  /// "frameFormat":n,"width":n,"height":n,"fps":n}
  /// A verification that times out stops the stream. A native start that
  /// fails may leave a previous stream running, as uvc_start_preview does.
  int uvc_request_start(
    ffi.Pointer<uvc_session_t> session,
    uvc_mode_t mode,
    int policy,
    int consecutive_frames,
    int timeout_ms,
  ) {
    return _uvc_request_start(
      session,
      mode,
      policy,
      consecutive_frames,
      timeout_ms,
    );
  }

  late final _uvc_request_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<uvc_session_t>,
            uvc_mode_t,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('uvc_request_start');
  late final _uvc_request_start = _uvc_request_startPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, uvc_mode_t, int, int, int)
      >();

  /// Queues a start that tries the modes in order until one verifies. With
  /// modes == NULL the worker takes the device's modes, MJPEG first, then by
  /// area and fps, ascending when prefer_quality is 0 and descending
  /// otherwise, never H.264, at most max_candidates of them. Stops after a
  /// success, an interrupted or no-device attempt, or when a later request
  /// exists. Result JSON: {"attempts":[<start result>, ...]}
  int uvc_request_start_auto(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<uvc_mode_t> modes,
    int mode_count,
    int prefer_quality,
    int max_candidates,
    int policy,
    int consecutive_frames,
    int timeout_ms,
  ) {
    return _uvc_request_start_auto(
      session,
      modes,
      mode_count,
      prefer_quality,
      max_candidates,
      policy,
      consecutive_frames,
      timeout_ms,
    );
  }

  late final _uvc_request_start_autoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<uvc_mode_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('uvc_request_start_auto');
  late final _uvc_request_start_auto = _uvc_request_start_autoPtr
      .asFunction<
        int Function(
          ffi.Pointer<uvc_session_t>,
          ffi.Pointer<uvc_mode_t>,
          int,
          int,
          int,
          int,
          int,
          int,
        )
      >();

  int uvc_request_stop(ffi.Pointer<uvc_session_t> session) {
    return _uvc_request_stop(session);
  }

  late final _uvc_request_stopPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_request_stop');
  late final _uvc_request_stop = _uvc_request_stopPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  int uvc_request_close(ffi.Pointer<uvc_session_t> session) {
    return _uvc_request_close(session);
  }

  late final _uvc_request_closePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_request_close');
  late final _uvc_request_close = _uvc_request_closePtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// Queues the teardown. Requests still queued complete with
  /// UVC_ERROR_NO_DEVICE, then this one completes once the device is closed,
  /// and the session is freed after that. Every later request is refused.
  /// The session pointer must not be used once this has completed.
  int uvc_request_destroy(ffi.Pointer<uvc_session_t> session) {
    return _uvc_request_destroy(session);
  }

  late final _uvc_request_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_request_destroy');
  late final _uvc_request_destroy = _uvc_request_destroyPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// Id of the most recently queued request, 0 before the first. A caller
  /// that wants to act only if nothing else was requested since (a stall
  /// restart) passes it as expected_latest to uvc_request_start_if.
  int uvc_latest_request_id(ffi.Pointer<uvc_session_t> session) {
    return _uvc_latest_request_id(session);
  }

  late final _uvc_latest_request_idPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_latest_request_id');
  late final _uvc_latest_request_id = _uvc_latest_request_idPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// uvc_request_start that returns UVC_ERROR_INTERRUPTED without queuing
  /// when the latest request id is not expected_latest.
  int uvc_request_start_if(
    ffi.Pointer<uvc_session_t> session,
    int expected_latest,
    uvc_mode_t mode,
    int policy,
    int consecutive_frames,
    int timeout_ms,
  ) {
    return _uvc_request_start_if(
      session,
      expected_latest,
      mode,
      policy,
      consecutive_frames,
      timeout_ms,
    );
  }

  late final _uvc_request_start_ifPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int64 Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Int64,
            uvc_mode_t,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('uvc_request_start_if');
  late final _uvc_request_start_if = _uvc_request_start_ifPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, int, uvc_mode_t, int, int, int)
      >();

  /// Copies the result JSON of a completed start or auto request and drops
  /// it. Returns bytes written, or 0 when there is none or it does not fit,
  /// in which case it is kept for a larger buffer.
  int uvc_take_request_result_json(
    ffi.Pointer<uvc_session_t> session,
    int request_id,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_take_request_result_json(
      session,
      request_id,
      buffer,
      buffer_length,
    );
  }

  late final _uvc_take_request_result_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Int64,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_take_request_result_json');
  late final _uvc_take_request_result_json = _uvc_take_request_result_jsonPtr
      .asFunction<
        int Function(
          ffi.Pointer<uvc_session_t>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// Count of stream errors the session reported since creation.
  int uvc_error_count(ffi.Pointer<uvc_session_t> session) {
    return _uvc_error_count(session);
  }

  late final _uvc_error_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int64 Function(ffi.Pointer<uvc_session_t>)>
      >('uvc_error_count');
  late final _uvc_error_count = _uvc_error_countPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// Modes the open device reports. Returns the count written, at most
  /// max_modes, or a negative error code.
  int uvc_get_supported_modes(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<uvc_mode_t> out_modes,
    int max_modes,
  ) {
    return _uvc_get_supported_modes(session, out_modes, max_modes);
  }

  late final _uvc_get_supported_modesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<uvc_mode_t>,
            ffi.Int,
          )
        >
      >('uvc_get_supported_modes');
  late final _uvc_get_supported_modes = _uvc_get_supported_modesPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<uvc_mode_t>, int)
      >();

  void uvc_set_platform_listener(
    ffi.Pointer<uvc_platform_listener_t> listener,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _uvc_set_platform_listener(listener, user_data);
  }

  late final _uvc_set_platform_listenerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<uvc_platform_listener_t>,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('uvc_set_platform_listener');
  late final _uvc_set_platform_listener = _uvc_set_platform_listenerPtr
      .asFunction<
        void Function(
          ffi.Pointer<uvc_platform_listener_t>,
          ffi.Pointer<ffi.Void>,
        )
      >();

  int uvc_get_stream_stats_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_stream_stats_json(session, buffer, buffer_length);
  }

  late final _uvc_get_stream_stats_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_stream_stats_json');
  late final _uvc_get_stream_stats_json = _uvc_get_stream_stats_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_get_supported_modes_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_supported_modes_json(session, buffer, buffer_length);
  }

  late final _uvc_get_supported_modes_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_supported_modes_json');
  late final _uvc_get_supported_modes_json = _uvc_get_supported_modes_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Last error text of the session. Valid until the session is destroyed.
  ffi.Pointer<ffi.Char> uvc_last_error(ffi.Pointer<uvc_session_t> session) {
    return _uvc_last_error(session);
  }

  late final _uvc_last_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<uvc_session_t>)
        >
      >('uvc_last_error');
  late final _uvc_last_error = _uvc_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<uvc_session_t>)>();

  /// Process-wide native log level (UVC_LOG_LEVEL_*).
  void uvc_set_log_level(int level) {
    return _uvc_set_log_level(level);
  }

  late final _uvc_set_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'uvc_set_log_level',
      );
  late final _uvc_set_log_level = _uvc_set_log_levelPtr
      .asFunction<void Function(int)>();

  /// Preview transform: rotation is 0, 90, 180, or 270 (clockwise degrees).
  /// flip_h mirrors the output left-right; flip_v mirrors it top-bottom.
  /// Transforms are applied during preview blit to the attached Flutter Texture
  /// and do not affect the RGBA buffer returned by copyLatestFrame.
  void uvc_set_preview_transform(
    ffi.Pointer<uvc_session_t> session,
    int rotation,
    int flip_h,
    int flip_v,
  ) {
    return _uvc_set_preview_transform(session, rotation, flip_h, flip_v);
  }

  late final _uvc_set_preview_transformPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('uvc_set_preview_transform');
  late final _uvc_set_preview_transform = _uvc_set_preview_transformPtr
      .asFunction<void Function(ffi.Pointer<uvc_session_t>, int, int, int)>();

  /// Reads back the current preview transform. Desktop plugin layers use this to
  /// render the attached Flutter texture with the same transform the preview
  /// blit applies. Null out-pointers are allowed.
  void uvc_get_preview_transform(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Int> rotation,
    ffi.Pointer<ffi.Int> flip_h,
    ffi.Pointer<ffi.Int> flip_v,
  ) {
    return _uvc_get_preview_transform(session, rotation, flip_h, flip_v);
  }

  late final _uvc_get_preview_transformPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('uvc_get_preview_transform');
  late final _uvc_get_preview_transform = _uvc_get_preview_transformPtr
      .asFunction<
        void Function(
          ffi.Pointer<uvc_session_t>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  /// Encodes the latest preview frame to JPEG.
  /// rotation/flip semantics match uvc_copy_latest_frame_rgba_transformed and are
  /// applied before encoding; quality is clamped to 1-100. Returns the number of
  /// JPEG bytes written to buffer, or 0 on failure (no frame yet, buffer too
  /// small, or encoder error; see uvc_last_error). out_width/out_height report
  /// the encoded (post-transform) dimensions; out_sequence reports the source
  /// frame sequence.
  int uvc_take_picture_jpeg(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
    int quality,
    int rotation,
    int flip_h,
    int flip_v,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
    ffi.Pointer<ffi.Int64> out_sequence,
  ) {
    return _uvc_take_picture_jpeg(
      session,
      buffer,
      buffer_length,
      quality,
      rotation,
      flip_h,
      flip_v,
      out_width,
      out_height,
      out_sequence,
    );
  }

  late final _uvc_take_picture_jpegPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('uvc_take_picture_jpeg');
  late final _uvc_take_picture_jpeg = _uvc_take_picture_jpegPtr
      .asFunction<
        int Function(
          ffi.Pointer<uvc_session_t>,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          int,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int64>,
        )
      >();

  /// Video recording (MP4 / H.264).
  ///
  /// Records the session's preview stream to an MP4 file while the preview
  /// keeps running. Requires an active preview: the recording locks onto the
  /// current frame dimensions, and frames whose dimensions later stop matching
  /// (e.g. after a mode switch) are dropped. rotation/flip semantics match
  /// uvc_take_picture_jpeg and are captured at start; the transform stays fixed
  /// for the whole recording. Recording is finalized automatically when the
  /// preview stops or the device closes.
  ///
  /// path is UTF-8. bitrate_bps <= 0 selects a default from resolution and fps.
  /// fps_hint <= 0 defaults to 30; it seeds encoder rate control while sample
  /// timestamps always follow actual frame arrival times.
  /// Returns 0 on success or a negative libuvc-style error code.
  int uvc_start_recording(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Char> path,
    int bitrate_bps,
    int fps_hint,
    int rotation,
    int flip_h,
    int flip_v,
  ) {
    return _uvc_start_recording(
      session,
      path,
      bitrate_bps,
      fps_hint,
      rotation,
      flip_h,
      flip_v,
    );
  }

  late final _uvc_start_recordingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('uvc_start_recording');
  late final _uvc_start_recording = _uvc_start_recordingPtr
      .asFunction<
        int Function(
          ffi.Pointer<uvc_session_t>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
          int,
          int,
        )
      >();

  /// Stops recording, drains the encoder, and finalizes the MP4 file.
  /// Returns 0 when the file was finalized, negative on failure. Calling with no
  /// active recording returns 0.
  int uvc_stop_recording(ffi.Pointer<uvc_session_t> session) {
    return _uvc_stop_recording(session);
  }

  late final _uvc_stop_recordingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<uvc_session_t>)>>(
        'uvc_stop_recording',
      );
  late final _uvc_stop_recording = _uvc_stop_recordingPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  int uvc_is_recording(ffi.Pointer<uvc_session_t> session) {
    return _uvc_is_recording(session);
  }

  late final _uvc_is_recordingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<uvc_session_t>)>>(
        'uvc_is_recording',
      );
  late final _uvc_is_recording = _uvc_is_recordingPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>)>();

  /// Returns JSON array of all controls the device supports, with min/max/def/cur/res fields.
  /// Returns number of bytes written, or 0 on failure.
  int uvc_ctrl_get_all_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_ctrl_get_all_json(session, buffer, buffer_length);
  }

  late final _uvc_ctrl_get_all_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_ctrl_get_all_json');
  late final _uvc_ctrl_get_all_json = _uvc_ctrl_get_all_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Returns JSON array of controls present in descriptor bmControls only.
  /// Debug helper: does not probe GET_CUR/GET_MIN/GET_MAX.
  int uvc_ctrl_get_bm_controls_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_ctrl_get_bm_controls_json(session, buffer, buffer_length);
  }

  late final _uvc_ctrl_get_bm_controls_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_ctrl_get_bm_controls_json');
  late final _uvc_ctrl_get_bm_controls_json = _uvc_ctrl_get_bm_controls_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Returns the current value of a control. Returns INT32_MIN on error.
  int uvc_ctrl_get(ffi.Pointer<uvc_session_t> session, int ctrl_id) {
    return _uvc_ctrl_get(session, ctrl_id);
  }

  late final _uvc_ctrl_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<uvc_session_t>, ffi.Int)
        >
      >('uvc_ctrl_get');
  late final _uvc_ctrl_get = _uvc_ctrl_getPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int)>();

  /// Sets a control value. Returns 0 (UVC_SUCCESS) on success, negative on error.
  int uvc_ctrl_set(ffi.Pointer<uvc_session_t> session, int ctrl_id, int value) {
    return _uvc_ctrl_set(session, ctrl_id, value);
  }

  late final _uvc_ctrl_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Int, ffi.Int32)
        >
      >('uvc_ctrl_set');
  late final _uvc_ctrl_set = _uvc_ctrl_setPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int)>();

  /// Compound controls that cannot be represented as a single integer value.
  int uvc_get_white_balance_component_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_white_balance_component_json(
      session,
      buffer,
      buffer_length,
    );
  }

  late final _uvc_get_white_balance_component_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_white_balance_component_json');
  late final _uvc_get_white_balance_component_json =
      _uvc_get_white_balance_component_jsonPtr
          .asFunction<
            int Function(
              ffi.Pointer<uvc_session_t>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  int uvc_set_white_balance_component_values(
    ffi.Pointer<uvc_session_t> session,
    int blue,
    int red,
  ) {
    return _uvc_set_white_balance_component_values(session, blue, red);
  }

  late final _uvc_set_white_balance_component_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Uint16, ffi.Uint16)
        >
      >('uvc_set_white_balance_component_values');
  late final _uvc_set_white_balance_component_values =
      _uvc_set_white_balance_component_valuesPtr
          .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int)>();

  int uvc_get_focus_rel_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_focus_rel_json(session, buffer, buffer_length);
  }

  late final _uvc_get_focus_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_focus_rel_json');
  late final _uvc_get_focus_rel_json = _uvc_get_focus_rel_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_set_focus_rel_values(
    ffi.Pointer<uvc_session_t> session,
    int focus_rel,
    int speed,
  ) {
    return _uvc_set_focus_rel_values(session, focus_rel, speed);
  }

  late final _uvc_set_focus_rel_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Int8, ffi.Uint8)
        >
      >('uvc_set_focus_rel_values');
  late final _uvc_set_focus_rel_values = _uvc_set_focus_rel_valuesPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int)>();

  int uvc_get_zoom_rel_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_zoom_rel_json(session, buffer, buffer_length);
  }

  late final _uvc_get_zoom_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_zoom_rel_json');
  late final _uvc_get_zoom_rel_json = _uvc_get_zoom_rel_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_set_zoom_rel_values(
    ffi.Pointer<uvc_session_t> session,
    int zoom_rel,
    int digital_zoom,
    int speed,
  ) {
    return _uvc_set_zoom_rel_values(session, zoom_rel, digital_zoom, speed);
  }

  late final _uvc_set_zoom_rel_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Int8,
            ffi.Uint8,
            ffi.Uint8,
          )
        >
      >('uvc_set_zoom_rel_values');
  late final _uvc_set_zoom_rel_values = _uvc_set_zoom_rel_valuesPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int, int)>();

  int uvc_get_pantilt_abs_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_pantilt_abs_json(session, buffer, buffer_length);
  }

  late final _uvc_get_pantilt_abs_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_pantilt_abs_json');
  late final _uvc_get_pantilt_abs_json = _uvc_get_pantilt_abs_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_set_pantilt_abs_values(
    ffi.Pointer<uvc_session_t> session,
    int pan,
    int tilt,
  ) {
    return _uvc_set_pantilt_abs_values(session, pan, tilt);
  }

  late final _uvc_set_pantilt_abs_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Int32, ffi.Int32)
        >
      >('uvc_set_pantilt_abs_values');
  late final _uvc_set_pantilt_abs_values = _uvc_set_pantilt_abs_valuesPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int)>();

  int uvc_get_pantilt_rel_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_pantilt_rel_json(session, buffer, buffer_length);
  }

  late final _uvc_get_pantilt_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_pantilt_rel_json');
  late final _uvc_get_pantilt_rel_json = _uvc_get_pantilt_rel_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_set_pantilt_rel_values(
    ffi.Pointer<uvc_session_t> session,
    int pan_rel,
    int pan_speed,
    int tilt_rel,
    int tilt_speed,
  ) {
    return _uvc_set_pantilt_rel_values(
      session,
      pan_rel,
      pan_speed,
      tilt_rel,
      tilt_speed,
    );
  }

  late final _uvc_set_pantilt_rel_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Int8,
            ffi.Uint8,
            ffi.Int8,
            ffi.Uint8,
          )
        >
      >('uvc_set_pantilt_rel_values');
  late final _uvc_set_pantilt_rel_values = _uvc_set_pantilt_rel_valuesPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, int, int, int, int)
      >();

  int uvc_get_roll_rel_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_roll_rel_json(session, buffer, buffer_length);
  }

  late final _uvc_get_roll_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_roll_rel_json');
  late final _uvc_get_roll_rel_json = _uvc_get_roll_rel_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_set_roll_rel_values(
    ffi.Pointer<uvc_session_t> session,
    int roll_rel,
    int speed,
  ) {
    return _uvc_set_roll_rel_values(session, roll_rel, speed);
  }

  late final _uvc_set_roll_rel_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<uvc_session_t>, ffi.Int8, ffi.Uint8)
        >
      >('uvc_set_roll_rel_values');
  late final _uvc_set_roll_rel_values = _uvc_set_roll_rel_valuesPtr
      .asFunction<int Function(ffi.Pointer<uvc_session_t>, int, int)>();

  int uvc_get_digital_window_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_digital_window_json(session, buffer, buffer_length);
  }

  late final _uvc_get_digital_window_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_digital_window_json');
  late final _uvc_get_digital_window_json = _uvc_get_digital_window_jsonPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  int uvc_set_digital_window_values(
    ffi.Pointer<uvc_session_t> session,
    int window_top,
    int window_left,
    int window_bottom,
    int window_right,
    int num_steps,
    int num_steps_units,
  ) {
    return _uvc_set_digital_window_values(
      session,
      window_top,
      window_left,
      window_bottom,
      window_right,
      num_steps,
      num_steps_units,
    );
  }

  late final _uvc_set_digital_window_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
          )
        >
      >('uvc_set_digital_window_values');
  late final _uvc_set_digital_window_values = _uvc_set_digital_window_valuesPtr
      .asFunction<
        int Function(ffi.Pointer<uvc_session_t>, int, int, int, int, int, int)
      >();

  int uvc_get_region_of_interest_json(
    ffi.Pointer<uvc_session_t> session,
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_region_of_interest_json(session, buffer, buffer_length);
  }

  late final _uvc_get_region_of_interest_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('uvc_get_region_of_interest_json');
  late final _uvc_get_region_of_interest_json =
      _uvc_get_region_of_interest_jsonPtr
          .asFunction<
            int Function(
              ffi.Pointer<uvc_session_t>,
              ffi.Pointer<ffi.Uint8>,
              int,
            )
          >();

  int uvc_set_region_of_interest_values(
    ffi.Pointer<uvc_session_t> session,
    int roi_top,
    int roi_left,
    int roi_bottom,
    int roi_right,
    int auto_controls,
  ) {
    return _uvc_set_region_of_interest_values(
      session,
      roi_top,
      roi_left,
      roi_bottom,
      roi_right,
      auto_controls,
    );
  }

  late final _uvc_set_region_of_interest_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<uvc_session_t>,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
          )
        >
      >('uvc_set_region_of_interest_values');
  late final _uvc_set_region_of_interest_values =
      _uvc_set_region_of_interest_valuesPtr
          .asFunction<
            int Function(ffi.Pointer<uvc_session_t>, int, int, int, int, int)
          >();
}

final class uvc_session extends ffi.Opaque {}

/// One camera per session. Sessions share nothing except the log level.
/// Every call may arrive on any thread, including several threads for one
/// session, and backends serialize internally. Listeners may run on native
/// threads. A NULL session behaves like a closed one. Int-returning calls return
/// UVC_ERROR_INVALID_PARAM (-2), uvc_ctrl_get returns INT32_MIN, JSON writers
/// return 0, and uvc_last_error returns "".
typedef uvc_session_t = uvc_session;
typedef uvc_frame_listener_tFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data, ffi.Int64 sequence);
typedef Dartuvc_frame_listener_tFunction =
    void Function(ffi.Pointer<ffi.Void> user_data, int sequence);

/// Listeners run on native threads and receive user_data unchanged. A NULL
/// listener clears the slot and returns only after a call in progress has
/// finished, so user_data may be freed afterwards. A listener must not call
/// back into this ABI. Both slots survive uvc_close_device.
typedef uvc_frame_listener_t =
    ffi.Pointer<ffi.NativeFunction<uvc_frame_listener_tFunction>>;
typedef uvc_error_listener_tFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<ffi.Char> message,
    );
typedef Dartuvc_error_listener_tFunction =
    void Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<ffi.Char> message,
    );
typedef uvc_error_listener_t =
    ffi.Pointer<ffi.NativeFunction<uvc_error_listener_tFunction>>;

final class uvc_mode_t extends ffi.Struct {
  @ffi.Int()
  external int frame_format;

  @ffi.Int()
  external int width;

  @ffi.Int()
  external int height;

  @ffi.Int()
  external int fps;
}

typedef uvc_request_listener_tFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Int64 request_id,
      ffi.Int op,
      ffi.Int result,
    );
typedef Dartuvc_request_listener_tFunction =
    void Function(
      ffi.Pointer<ffi.Void> user_data,
      int request_id,
      int op,
      int result,
    );

/// Runs on the worker thread. op is a UVC_REQUEST_* value and result the
/// request's return code. Must not call back into this ABI.
typedef uvc_request_listener_t =
    ffi.Pointer<ffi.NativeFunction<uvc_request_listener_tFunction>>;

/// ---------------------------------------------------------------------------
/// Platform listener. Process-wide, set once by the platform plugin. The
/// callbacks run on any thread, including the worker and the thread that
/// destroys a session, and must not call back into this ABI. Setting NULL
/// returns only after a callback in progress has finished.
/// ---------------------------------------------------------------------------
final class uvc_platform_listener_t extends ffi.Struct {
  /// The session no longer uses the fd it took through uvc_supply_fd for
  /// this request. The platform closes it here and nowhere else.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> user_data,
        ffi.Uint64 session_id,
        ffi.Int64 request_id,
      )
    >
  >
  device_released;

  /// The session id is gone for good. Fires once per destroyed session.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void> user_data, ffi.Uint64 session_id)
    >
  >
  session_destroyed;
}

const int UVC_REQUEST_OPEN = 1;

const int UVC_REQUEST_START = 2;

const int UVC_REQUEST_START_AUTO = 3;

const int UVC_REQUEST_STOP = 4;

const int UVC_REQUEST_CLOSE = 5;

const int UVC_REQUEST_DESTROY = 6;

const int UVC_VERIFY_NONE = 0;

const int UVC_VERIFY_STABLE_FRAMES = 1;

const int UVC_VERIFY_SEQUENCE_ONLY = 2;

const int UVC_CTRL_ID_BRIGHTNESS = 1;

const int UVC_CTRL_ID_CONTRAST = 2;

const int UVC_CTRL_ID_HUE = 3;

const int UVC_CTRL_ID_SATURATION = 4;

const int UVC_CTRL_ID_SHARPNESS = 5;

const int UVC_CTRL_ID_GAMMA = 6;

const int UVC_CTRL_ID_GAIN = 7;

const int UVC_CTRL_ID_BACKLIGHT_COMPENSATION = 8;

const int UVC_CTRL_ID_WHITE_BALANCE_TEMPERATURE = 9;

const int UVC_CTRL_ID_WHITE_BALANCE_TEMP_AUTO = 10;

const int UVC_CTRL_ID_POWER_LINE_FREQUENCY = 11;

const int UVC_CTRL_ID_CONTRAST_AUTO = 12;

const int UVC_CTRL_ID_HUE_AUTO = 13;

const int UVC_CTRL_ID_WHITE_BALANCE_COMPONENT_AUTO = 14;

const int UVC_CTRL_ID_DIGITAL_MULTIPLIER = 15;

const int UVC_CTRL_ID_DIGITAL_MULTIPLIER_LIMIT = 16;

const int UVC_CTRL_ID_ANALOG_VIDEO_STANDARD = 17;

const int UVC_CTRL_ID_ANALOG_LOCK_STATUS = 18;

const int UVC_CTRL_ID_EXPOSURE_ABS = 20;

const int UVC_CTRL_ID_AE_MODE = 21;

const int UVC_CTRL_ID_AE_PRIORITY = 22;

const int UVC_CTRL_ID_FOCUS_ABS = 23;

const int UVC_CTRL_ID_FOCUS_AUTO = 24;

const int UVC_CTRL_ID_ZOOM_ABS = 25;

const int UVC_CTRL_ID_SCANNING_MODE = 26;

const int UVC_CTRL_ID_EXPOSURE_REL = 27;

const int UVC_CTRL_ID_IRIS_ABS = 28;

const int UVC_CTRL_ID_IRIS_REL = 29;

const int UVC_CTRL_ID_ROLL_ABS = 30;

const int UVC_CTRL_ID_PRIVACY = 31;

const int UVC_CTRL_ID_FOCUS_SIMPLE = 32;
